name: CI
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: speelbarrow/checkout-and-setup@v1
      - name: Run tests
        run: cargo test --workspace --all-features
